HBlog/config/routes.rb
HBlog::Application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
    resources :votes
  end

  get "welcome/index"

  root 'welcome#index'

end

HBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

HBlog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
  					length: { minimum: 5 }
  has_many :votes
  belongs_to :user

  def votes_total
     return nil if (upvotes + downvotes).empty?
     upvotes.size - downvotes.size
  end
 
  private

  	def upvotes
      votes.up
    end
 
    def downvotes
      votes.down
    end


end

HBlog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :posts
end

HBlog/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post

  scope :up, -> { where(direction: 'up') }
  scope :down, -> { where(direction: 'down') }

end

HBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	def after_sign_in_path_for(posts)
	  posts_path
	end


end

HBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_permission, only: [:update,:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user: current_user))
    redirect_to post_path(@post)
  end
 
  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end


private
  def check_permission
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.user != current_user
      flash.alert = "Not your comment"
      redirect_to post_path(@post)
    end
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

HBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]
before_action :check_permission, only: [:update, :destroy]

def index
  @posts = Post.all
end


def new
  @post = Post.new
end


def edit
  @post = Post.find(params[:id])
end


def create
  @post = Post.new(params[:post].permit(:title, :text).merge(user: current_user))

  if @post.save
  	redirect_to @post
  else
  	render 'new'
  end
end


def update
  @post = Post.find(params[:id])
 
  if @post.update(params[:post].permit(:title, :text))
    redirect_to @post
  else
    render 'edit'
  end
end


def show
  @post = Post.find(params[:id])
  @comment = @post.comments.build
end


def destroy
  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to posts_path
end



private
 def check_permission
    @post = Post.find(params[:id])

    if @post.user != current_user
      flash.alert = "Not your post"
      redirect_to post_path(@post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end


end

HBlog/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

HBlog/app/controllers/votes_controller.rb
class VotesController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

	def create
	    @post = Post.find params[:post_id]
	    @post.votes.create(direction: params[:direction])
	 
	    render json: { id: @post.id, votes: @post.votes_total }
	end

end

HBlog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

HBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

HBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

HBlog/app/helpers/posts_helper.rb
module PostsHelper
  
  def vote_button(post, direction, link_text)
  	button_to link_text, post_votes_path(post, direction: direction, format: :json), remote: true
  end
end

HBlog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

HBlog/app/views/comments/_comment.html.erb
<% if comment.persisted? %>
  <p>
    <strong>Name:</strong>
    <%= comment.commenter %>
 <br>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
  <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
  <br>
  <%= link_to 'Delete Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

  </p>
<% end %>

HBlog/app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

HBlog/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

HBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>


<%= yield %>

</body>
</html>

HBlog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

HBlog/app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

HBlog/app/views/posts/index.html.erb
<div style="width:600px; margin: 0 auto;">
<h1>All Posts</h1>
<%= link_to 'New post', new_post_path %> 
<br><br>
<table> 
<% @posts.each do |post| %>
  <tr>
    <td><strong><%= post.title %></strong>
      &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
       <em>Popularity: <%= post.votes_total %></em>
       &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
       <em>Comments: <%= post.comments.count %></em> 
    </td>
  </tr>
  <tr>
    <td style="width:600px;"><%= post.text %></td>
  </tr>
  <tr>
    <td><%= link_to 'Show', post %>  |
        <%= link_to 'Edit', edit_post_path(post) %>  |
        <%= link_to 'Delete', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
                    <br><br></td>
  </tr>
<% end %>
</table>
</div>

HBlog/app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

HBlog/app/views/posts/show.html.erb
<div style="width:500px;">
	<h2><%= @post.title %></h2> 
	<p><%= @post.text %></p>
</div>

<br>


<p>Total Votes:
<span class="vote_count" data-id='<%= @post.id %>'><%= @post.votes_total %></span>
</p>
<%= vote_button @post, 'up', '+1' %>
<%= vote_button @post, 'down', '-1' %>




<br> 
<p><strong><u>Comments:</u></strong></p>
<%= render @post.comments %>

<table style="border: 1px solid black; width:200px;">
<tr>
  <td>
	<p><strong>Add a comment:</strong></p>
	<%= render "comments/form" %>
 </td>
</tr>
</table>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>	

HBlog/app/views/welcome/index.html.erb
<center>
<h1>Welcome to HBlog.</h1>
<p>The blogging platform made by Hemang, for Hemang</p>
<%= link_to "My Blog", controller: "posts" %>
<br>
<%= link_to 'New post', new_post_path %> 
<br>
<br>
<%= link_to 'Sign Up', new_user_registration_path %>
<br>
<%= link_to 'Login', new_user_session_path %>

</center>